title: Fake News Analytics for Tweets
logo: /assets/img/logo2.png
description: This is a Fake News Analytics for Tweets in Real Time course.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
