title: Fake News Analytics for Tweets
logo: /assets/img/lo.png
description: This is a Fake News Analytics for Tweets Ching-Chieh Huang in Real Time course 
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
markdown: GFM
